src/mates_rates/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tools do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:index, :show, :update, :destroy, :edit]
  
  post '/search', to: 'pages#redirect_to_results', as: 'redirect_to_results'
  get '/search/:query', to: 'pages#results', as: 'results'
  get '/browse', to: 'tools#index', as: 'browse'
  get '/home', to: 'pages#home', as: 'home'
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/my_rentals', to: 'pages#my_rentals', as: 'my_rentals'
  get '/my_tools', to: 'pages#my_tools', as: 'my_tools'
  get '/admin', to: 'pages#admin', as: 'admin_dash'
  get '/search', to: 'pages#search', as: 'search'
  get '/users/:id', to: 'users#show', as: 'user'
  

  root "pages#home"

  
end

src/mates_rates/app/views/pages/_rental.html.erb
    <% if rental.user == current_user %>
    <p>Renting  <%= link_to "#{rental.tool.name}", rental_url(rental) %> off <%= link_to "#{rental.tool.user.first_name}", user_url(rental.tool.user) %></p>
    <% else %>
    <p>Renting <%= link_to "#{rental.tool.name}", rental_url(rental) %> to <%= link_to "#{rental.tool.user.first_name}" %></p>
    <% end %>
    <p>From <%= rental.start_date %> to <%= rental.end_date %> </p>
    <p>Cost: $<%= rental.price %>, <%= rental.delivery_option %><% if rental.delivery_option == 'Delivery' %>: $<%= rental.delivery_fee %><% end %>
    
      <% if can? :delete, rental %>
        <%= link_to 'Manage Rental', edit_rental_url(rental), class: "secondary-content btn-small waves-effect waves-light"%>
      <% elsif can? :edit, rental %>
        <%= link_to 'Manage Rental', edit_rental_url(rental), class: "secondary-content btn-small waves-effect waves-light"%>
        
      <% end %>
      <%= link_to 'View Details', rental_url(rental), class: "red darken-2 secondary-content btn-small waves-effect waves-light"%>
  

src/mates_rates/app/views/pages/admin.html.erb
<h1>Admin Dashboard</h1>

<div class="card">
<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s6"><a href="#tools">Tools</a></li>
        <li class="tab col s6"><a href="#rentals">Rentals</a></li>
      </ul>
    </div>

<div id="tools" class="col s12">
  <h5 class="center-align"> Tools </h5>
  <ul class="collection">
    <% @tools.each do |tool| %>
    <li class="collection-item">
        <p><%= tool.name %> - <%= tool.brand %>-<% if tool.model %><%= tool.model %><% end %>
        - <span class="red-text">$<%= tool.price %>/day</span></p>
        <p>Owned by <%= link_to "#{tool.user.first_name}", user_url(tool.user), class: "red-text" %>
        | 
        <% if tool.delivery_options == 'Both' || tool.delivery_options == 'Delivery' %>
            Delivery Available - $<%= tool.delivery_fee%>/km
            <% else %>
            Pickup Only
        <% end %>
        <%= link_to 'Manage Tool', edit_tool_url(tool), class: "secondary-content btn-small light-blue waves-effect waves-light white-text darken-3"%>
  </p>
        
    </li>
  <% end %>
  </ul>
</div>


<div id="rentals" class="col s12">
<h5 class="center-align">Rentals</h5>
<ul class="collection">
    <% @rentals.each do |rental| %>
    <li class="collection-item">
    <p><%= link_to "#{rental.tool.user.first_name}", user_url(rental.tool.user) %> renting  <%= link_to "#{rental.tool.name}", rental_url(rental) %> to <%= link_to "#{rental.user.first_name}", user_url(rental.user) %></p>
    
    <p>From <%= rental.start_date %> to <%= rental.end_date %> </p>
    <p>Cost: $<%= rental.price %>, <%= rental.delivery_option %><% if rental.delivery_option == 'Delivery' %>: $<%= rental.delivery_fee %><% end %>
    
        <%= link_to 'Manage Rental', edit_rental_url(rental), class: "secondary-content light-blue darken-3 btn-small waves-effect waves-light"%>
      </p>
    </li>
    <% end %>
</ul>
</div>
</div>

src/mates_rates/app/views/pages/home.html.erb
  <div class="hero white-text valign-wrapper">
  <div class="container">
  <div class="section">
    <h1 class="welcome"> Welcome to Mates Rates </h1>
    <h4 class="tagline"> Find affordable rental tools for your DIY project.</h4>
  </div>
  <div class="section">
  <% unless user_signed_in? %>
    <%= link_to 'Sign In', new_user_session_path, class: "btn-large waves-effect waves-light red darken-2" %>
    <%= link_to 'Sign Up', new_user_registration_path, class: "btn-large waves-effect waves-light teal darken-3" %>
  <% end %>

  <p class=" flow-text tagline">What are you looking for?</p>
  <%= form_with url: redirect_to_results_path, method: 'post' do |f| %>
      <div class="input-field">
        <%= f.text_field :query, id: 'search', type: 'search', class: "white" %>
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
</div>
      <% end %>

  </div>
</div>
  </div>
<h2 class="center-align">Recent Listings</h2>
<div class="section tools-list">
<%= render partial: 'shared/tools' %>
</div>

src/mates_rates/app/views/pages/my_rentals.html.erb
<div class="section">
<div class="card">
<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s6"><a href="#my-rentals">My Rentals</a></li>
        <li class="tab col s6"><a href="#my-tool-rentals">My Tool Rentals</a></li>
      </ul>
      </div>


<div class="row" id="my-rentals">
<div class="col s12">
<ul class="tabs">
      <li class="tab col s4"><a href="#my-future-rentals">Future</a></li>
      <li class="tab col s4"><a href="#my-current-rentals">Current</a></li>
      <li class="tab col s4"><a href="#my-past-rentals">Past</a></li>
</ul>
</div>

<div id="my-future-rentals" class="col s12">
<h5 class="center-align">Future Rentals</h5>
<ul class="collection">
<% unless @future.empty? %>
    <% @future.each do |rental| %>
    <li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>
    <% end %>
<% else %>
  <li class="collection-item"> No Future Rentals </li>
<% end %>
</ul>
</div>

<div id="my-past-rentals" class="col s12">
<h5 class="center-align">Past Rentals</h5>
<ul class="collection">
<% unless @past.empty? %>
<% @past.each do |rental| %>
<li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>

<% end %>
<% else %>
  <li class="collection-item"> No Future Rentals </li>
<% end %>
</ul>
</div>
<div id="my-current-rentals" class="col s12">
<h5 class="center-align">Current Rentals</h5>
<ul class="collection">
<% unless @current.empty? %>
<% @current.each do |rental| %>
<li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>
<% end %>
<% else %>
  <li class="collection-item"> No Future Rentals </li>
<% end %>
</ul>
</div>
</div>

<div class="row" id="my-tool-rentals">
<div class="col s12">
<ul class="tabs">
      <li class="tab col s4"><a href="#future-rentals">Future</a></li>
      <li class="tab col s4"><a href="#current-rentals">Current</a></li>
      <li class="tab col s4"><a href="#past-rentals">Past</a></li>
</ul>
</div>

<div id="future-rentals" class="col s12">
<h5 class="center-align">Future Rent Outs</h5>
<ul class="collection">
<% unless @future_rentals.empty? %>
    <% @future_rentals.each do |rental| %>
    <li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>
    <% end %>
<% else %>
  <li class="collection-item"> No Future Rent Outs </li>
<% end %>
</ul>
</div>

<div id="past-rentals" class="col s12">
<h5 class="center-align">Past Rent Outs</h5>
<ul class="collection">
<% unless @past_rentals.empty? %>
<% @past_rentals.each do |rental| %>
<li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>

<% end %>
<% else %>
  <li class="collection-item"> No Past Rent Outs </li>
<% end %>
</ul>
</div>
<div id="current-rentals" class="col s12">
<h5 class="center-align">Current Rent Outs</h5>
<ul class="collection">
<% unless @current_rentals.empty? %>
<% @current_rentals.each do |rental| %>
<li class="collection-item">
    <%= render 'rental', rental: rental %>
    </li>
<% end %>
<% else %>
  <li class="collection-item"> No Current Rent Outs </li>
<% end %>
</ul>
</div>
</div>

</div>
</div>
</div>
</div>

src/mates_rates/app/views/pages/my_tools.html.erb
<h2>My Tools</h2>
<div class="section tools-list">
<%= render 'shared/tools' %>
</div>

src/mates_rates/app/views/pages/profile.html.erb
<h2>My Profile</h2>
<div class="row">

<% if can? :create, Tool %>
  <%= link_to 'My Tools', my_tools_path, class: "btn waves-effect waves-light light-blue darken-3 s10 col offset-s1 m4" %>
  <%= link_to 'My Rentals', my_rentals_path, class: "btn waves-effect waves-light teal darken-3 col s10 offset-s1 m4" %>
  <%= link_to 'List a Tool', new_tool_path, class: "btn waves-effect waves-light light-blue darken-3 col s10 offset-s1 m4" %>
<% else %>
  <%= link_to 'My Tools', my_tools_path, class: "btn waves-effect waves-light light-blue darken-3 s10 col offset-s1 m5" %>
  <%= link_to 'My Rentals', my_rentals_path, class: "btn waves-effect waves-light light-blue darken-3 col s10 offset-s1 m5 offset-m2" %>
<% end %>
</div>

<h4>My Details</h4>
<ul class="collection">
<li class="collection-item">
<span>Name:</span><span class="secondary-content"><%= current_user.first_name %> <%= current_user.last_name%></span>
</li>
<li class="collection-item">
<span>Email:</span><span class="secondary-content"><%= current_user.email %></span>
</li>
<li class="collection-item">
<span>Address:</span><span class="secondary-content"><%= current_user.address %></span>
</li>
<li class="collection-item">
<span>Status:</span><span class="secondary-content"><%= current_user.roles.last.name.capitalize %> </span>
</li>
<li class="collection-item center-align">
<%= link_to 'Update Details', edit_user_registration_path, class: "btn waves-effect waves-light teal darken-2 col s10 offset-s1 m3 offset-m1" %>
</li>
</ul>

src/mates_rates/app/views/pages/results.html.erb
<h1>Search Results for: '<%= params[:query] %>'</h1>
<p>Here's what we could find..</p>

<% unless @tools.empty? %>
  <div class="section">
  <%= render partial: 'shared/tools' %>
  </div>
  <div class="divider"></div>
  <div class="section center-align">
  <h3>Not what you're looking for?</h3>
  <%= link_to 'Browse All Tools', tools_path, class:'btn waves-effect waves-light white-text' %><br>
  </div>
<% else %>
  <div class="section">
  <h2> No Results Found </h2>
  <%= link_to 'Browse All Tools', tools_path, class:'btn waves-effect waves-light white-text' %><br>
  </div>
<% end %>

src/mates_rates/app/views/pages/search.html.erb
<div class="section">
<h2>Search for a tool</h2>
<%= form_with url: redirect_to_results_path, method: 'post' do |f| %>
      <div class="input-field">
        <%= f.text_field :query, id: 'search', type: 'search' %>
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
</div>
      <% end %>
      </div>
<div class="section">
<h4>Just Looking?<h4>
<%= link_to 'Browse All Tools', tools_path, class: "btn-large waves-effect waves-light white-text" %>
</div>