src/mates_rates/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tools do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:index, :show, :update, :destroy, :edit]
  
  post '/search', to: 'pages#redirect_to_results', as: 'redirect_to_results'
  get '/search/:query', to: 'pages#results', as: 'results'
  get '/browse', to: 'tools#index', as: 'browse'
  get '/home', to: 'pages#home', as: 'home'
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/my_rentals', to: 'pages#my_rentals', as: 'my_rentals'
  get '/my_tools', to: 'pages#my_tools', as: 'my_tools'
  get '/admin', to: 'pages#admin', as: 'admin_dash'
  get '/search', to: 'pages#search', as: 'search'
  get '/users/:id', to: 'users#show', as: 'user'
  

  root "pages#home"

  
end

src/mates_rates/app/models/tool.rb
class Tool < ApplicationRecord

  # Tools belong to specific users.
  belongs_to :user

  # Tools can be rented out many times and therefore have many rentals.
  has_many :rentals

  # Tools belong to categories and categories contain many tools.
  has_and_belongs_to_many :categories

  # Tools have many renters based on their rentals - helper.
  has_many :renters, through: :rentals, source: :user

  # Tools can have a photo attached to them.
  has_one_attached :photo

  # Validates Tool options
  validates_associated :user
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true, length: { maximum: 20 }
  validates :brand, presence: true
  validates :photo, presence: true
  validates :availability, inclusion: { in: [true,false] }
  validates :delivery_options, presence: true, inclusion: {in: %w[Pickup Delivery Both]}
  validates :delivery_fee, presence: true, numericality: { less_than: 100 }
  validates :min_delivery_fee, presence: true

  # Method for grabbing the tool's unavailable dates.
  def unavailable_dates
    # Plucks the dates from the rentals and stores them
    rentals.pluck(:start_date, :end_date).map do |range|
      # Formats the data for flatpickr to read the unavailable dates.
      { from: range[0].to_s, to: range[1].to_s }
    end
  end

  # Method for searching tools based on queries provided by user.
  def self.search(query)
    # Check for query
    if query
      # Find all tools with a category similar to the query using ILIKE and stores.
      results1 = joins(:categories).where("categories.name ILIKE ? ", "%#{query}%")

      # Find all tools with a name, model or brand similar to the query using ILIKE and stores.
      results2 = where("(availability = 'true') AND (name ILIKE ? OR brand ILIKE ? OR model ILIKE ? )",  "%#{query}%", "%#{query}%", "%#{query}%")
      
      # Combines the values
      results = results1 + results2
      # Removes duplicates
      results.uniq!
    
      # Returns the list of tools that match the search query in some way.
      return results
    end
  end

end

src/mates_rates/app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  # Ensure the user is signed in before allowing tool manipulation.
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]

  def new
    # Authorisation - essentially checks for owner role.
    unless can? :create, Tool
      redirect_to('/browse', alert: 'You do not have permissions to view that page.')
    end
    # If authorised - intialize new tool instance
    @tool = Tool.new
  end

  # Logic for creating Tool
  def create
    # Initialize the new tool instance
    @tool = Tool.new(tool_params)

    # Set categories based on categories selected
    params[:tool][:categories].each do |category|
      # Convert to integer
      cat = category.to_i
      
      # Rails checkbox collection select passes through blank value to help handle user input
      # So we check that the current iteration isn't this blank value.
      if cat.positive?
        # Fetch the category from the database using the id of the current iteration and store it.
        @tool.categories << Category.find(cat)
      end
    end

    # Attach the uploaded photo
    @tool.photo.attach(tool_params[:photo])
    # Assign the tool to the current user
    @tool.user = current_user

    # Description is allowed to be blank, but we don't want it to be nil.
    unless @tool.description
      @tool.description = ""
    end

    # Model is allowed to be blank, but we don't want it to be nil.
    unless @tool.model
      @tool.model = ""
    end
    
    # Logic for valid creation check
    respond_to do |format|
      if @tool.save
        # Create tool and store
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        # Errors - try again
        format.html { render :new }
        format.json { render json: @tool.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # Tool Update
  def update
    # Grab the relevant tool from the database using the id passed in the params
    @tool = Tool.find(params[:id])

    # Logic for valid update check.
    respond_to do |format|
      if @tool.update(tool_params)
        # Get categories and update tool.
        params[:tool][:categories].each do |category|
          cat = category.to_i
          # Blank checkbox collection select value filtering
          if cat.positive?
            # Grabs the category from the database using the current iteration id and stores it.
            @tool.categories << Category.find(cat)
          end
        end
        # Update image if necessary.
        @tool.image.attach(tool_params[:image]) if tool_params[:image]
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # Logic for Tool editing
  def edit
    # Grab the relevant tool from the database using the id passed in the params
    @tool = Tool.find(params[:id])

     # Authorisation check
    if can? :edit, @tool
      @tool
    else
      # Failed permissions check redirect
      redirect_to('/browse', notice: 'You do not have permissions to view that page.')
    end
  end


  # Logic for showing Tool
  def show
    # Grab the relevant tool from the database using the id passed in the params
    @tool = Tool.find(params[:id])
    # Initialize variable for filtering
    @tools = []

    # Finding related tools
    # Loop through the tool's categories
    @tool.categories.each do |category|
      # Loop through the current category's tools
      category.tools.each do |tool|
        # For each tool that is available, store.
        if tool.availability == true
          @tools << tool
        end
      end
    end

    # Make sure we've got enough tools, otherwise grab latest.
    if @tools.length < 4
      # Grabs the last four tools in the database based on their order (in this case, creation date)
      @tools = Tool.last(4)
    else
      @tools.uniq!.last(4)
    end
  end

  # Pass through all available tools to the index page.
  def index
    # Grabs the relevant tools from the database by checking for the availability relation status.
      @tools = Tool.where(availability: true)
  end


  # Tools can't be destroyed because they are referenced by Rentals - that's why availability is an option.

  private

  # Sanitize tool creation params.
  def tool_params
    params.require(:tool).permit(:id, :price, :name, :brand, :model, :description, :availability, :delivery_options, :delivery_fee, :min_delivery_fee, :user_id, :photo)
  end


end

src/mates_rates/app/helpers/tools_helper.rb
module ToolsHelper
end

src/mates_rates/app/views/tools/_form.html.erb
<div class="row">
<div class="field col s12 m6">
    <%= form.label :price %>
    <%= form.number_field :price, in: 0..100, step: 1 %>
</div>

<div class="field col s12 m6">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
</div>

<div class="row">
<div class="field col s12 m6">
  <%= form.label :brand %>
  <%= form.text_field :brand %>
</div>

<div class="field col s12 m6">
  <%= form.label :model %>
  <%= form.text_field :model %>
</div>
</div>

<div class="row">
<div class="field col s12">
  <%= form.label :description %>
  <%= form.text_area :description, class: "materialize-textarea"%>
</div>
</div>
<div class="row">
<div class="field col s12 m4">
  <%= form.label :delivery_options %>
  <%= form.select(:delivery_options, ['Pickup','Delivery','Both']) %>
</div>

<div class="field col s12 m4">
  <%= form.label :delivery_fee %>
  <%= form.number_field :delivery_fee, in: 0..100, step: 0.25 %> 
</div>

<div class="field col s12 m4">
  <%= form.label :min_delivery_fee %>
  <%= form.number_field :min_delivery_fee, in: 0..1000, step: 1 %> 
</div>
</div>



<div class="row">
<div class="field col s12">
<%= form.label "Select Categories" %><br>
<ul id="category-checkboxes">
  <%= form.collection_check_boxes(:categories, Category.all, :id, :name, {checked: @tool.categories.map(&:to_param)}) do |b| %>
   <li>
    <label>
  <%= b.check_box class: "filled-in col s1", id: 'available' %>
<span> <%= b.text %> </span>
  </label>
  </li>
  
  <%# <label>
     <%= b.check_box class >
    <%= b.label(:"data-value" => b.value) { b.check_box } >
    <span><%= b.text ></span>
    </label> %>
  <% end %>
  <ul>
</div>
</div>
<div class="row">
    
    <div class="file-field input-field col s12">
    <label>Photo Upload</label>
    <%= form.file_field :photo, class: "btn col s6 waves-effect waves-light white-text" %>
    <input class="file-path validate col s6" type="text"/>
    </div>
 </div>
<div class="row">
<div id="availability-field" class="field">
<label>
  <%= form.check_box :availability, class: "filled-in", id: 'available' %>
<span> This tool is available for rentals now. </span>
  </label>
  <%# <%= form.label :availability, for: 'available', id: 'available' %> 
</div>
</div>
<div class="row" style="text-align: center;">
    <button class="btn-large waves-effect waves-light white-text" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
    </div>
    
</div>

  

src/mates_rates/app/views/tools/edit.html.erb
<h1>Update your Tool</h1>
<p>Complete the form below to update your listing.</p>
<%= form_with(model: @tool, url: tool_path(@tool), local: true) do |form| %>
  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= render 'form', form: form %>
  <% end %>

src/mates_rates/app/views/tools/index.html.erb
<h1>Tools#index</h1>
<p>Find me in app/views/tools/index.html.erb</p>
<%= render 'shared/tools' %>

src/mates_rates/app/views/tools/new.html.erb
<h1>List your Tool</h1>
<p>Complete the form below to list your tool and start earning money!</p>
<%= form_with(model: @tool, url: tools_path(@tool), local: true) do |form| %>
  <% if @tool.errors.any? %>
  <div class="section">
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>
  <div class="section">
  
  <%= render 'form', form: form %>
 
</div>
  <% end %>

src/mates_rates/app/views/tools/show.html.erb
<h2><%= @tool.name %></h2>
<div class="card sticky-action hoverable large horizontal">
    <div class="card-image">
      <% if @tool.photo.attached? %>
       <%= image_tag @tool.photo, class: "activator"%>
      <% end %>

    </div>
    <div class="card-content">
      <span class="card-title grey-text text-darken-4"><%= @tool.name %> - <%= @tool.brand %>-<% if @tool.model %><%= @tool.model %><% end %><i class="right red-text darken-4 card-title">$<%= @tool.price %>/day</i></span>
      
      <p>Owned by <%= link_to "#{@tool.user.first_name}", user_url(@tool.user), class: "red-text" %>
      | 
      <% if @tool.delivery_options == 'Both' || @tool.delivery_options == 'Delivery' %>
          Delivery Available - $<%= @tool.delivery_fee%>/km
          <% else %>
          Pickup Only
          <% end %></p>
      <p><%= @tool.description %></p>
    </div>
    <div class="card-action">
          <% if can? :edit, @tool %>
            <%= link_to 'Manage Tool', edit_tool_url(@tool), class: "light-blue waves-effect waves-light btn white-text darken-3"%>
          <% elsif can? :create, Rental %>
            <%= link_to 'Rent this Tool', new_tool_rental_path(@tool), class: "teal waves-effect waves-light btn white-text darken-1" %>
          <% else %>
            <%= link_to 'Sign in to rent this tool', new_user_session_path, class: "cyan waves-effect waves-light btn white-text darken-1" %>
          <% end %>
          
        </div>
  </div>


<div class="section tools-list">
<h3 class="section-title">Similar Tools</h3>
<%= render 'shared/tools' %>
</div>