src/mates_rates/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tools do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:index, :show, :update, :destroy, :edit]
  
  post '/search', to: 'pages#redirect_to_results', as: 'redirect_to_results'
  get '/search/:query', to: 'pages#results', as: 'results'
  get '/browse', to: 'tools#index', as: 'browse'
  get '/home', to: 'pages#home', as: 'home'
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/my_rentals', to: 'pages#my_rentals', as: 'my_rentals'
  get '/my_tools', to: 'pages#my_tools', as: 'my_tools'
  get '/admin', to: 'pages#admin', as: 'admin_dash'
  get '/search', to: 'pages#search', as: 'search'
  get '/users/:id', to: 'users#show', as: 'user'
  

  root "pages#home"

  
end

src/mates_rates/app/models/rental.rb
class Rental < ApplicationRecord
  include ApplicationHelper

  # Rentals belong to both a tool and a user. Without one or the other there is no point to the rental.
  belongs_to :tool
  belongs_to :user

  # Validations of Rental relations
  validates_associated :user
  validates_associated :tool
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :delivery_option, presence: true
  # Validates delivery option to ensure it matches with the tool.
  validate :valid_delivery_option
  # Availability is a custom validation
  # checks that there are no rentals of this tool with overlapping dates.
  validates :start_date, :end_date, presence: true, availability: true, on: :create
  # Custom validation - self explanatory.
  validate :end_date_after_start_date

  # Method for checking if a rental is finished.
def finished
  if self.end_date < Date.today
    return true
  else
    return false
  end
end

# Validates that the delivery option selected matfhes up with the tool.
def valid_delivery_option

  # Formats 'both' for checking
  if tool.delivery_options == 'Both'
    options = ['Delivery', 'Pickup']
  end

  # Checks the delivery option against tool delivery options
  if tool.delivery_options.include?(delivery_option) || options.include?(delivery_option)
    return true
  else
    # Failed validation error.
    errors.add(:delivery_option, 'is not available for this tool.')
  end
end
  

# Delivery fee calculation
  def calculate_fee(current_user)
    # No need to calculate the fee if pickup is the only available option.
    return if tool.delivery_options == 'Pickup'

    # Grabs the addresses and formats them to be used in an API call to Google.
    owner_address = tool.user.address.gsub(' ', '+')
    renter_address = current_user.address.gsub(' ', '+')

    # Calls the requestHelper method in application helper to simulate a request to the Google static API for distance/route calculations
    requestHelper("https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=#{renter_address}&destinations=#{owner_address}&key=#{Rails.application.credentials.google_places_api_key}") do |response|
      
      # Grabs the required data out of the response
      distance = response['rows'].first['elements'].first['distance']['value']
      
      # Sets the value based on the calculation of the fee using the distance value.
      # If the distance is below the minimum delivery fee, set it to the minimum.
      self.delivery_fee = [(tool.delivery_fee * distance/1000).round(2), tool.min_delivery_fee].max
    end
  end

  private

  # Validation method for checking valid dates.
  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    if end_date < start_date
      errors.add(:end_date, 'must be after the start date.')
    end
  end

end

src/mates_rates/app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  
  # Ensures the user is logged in before performing actions
  before_action :authenticate_user!
  
  # Logic for passing data to new rental page
  def new
  # Grabs the relevant tool from the database using the is passed in the params
   @tool = Tool.find(params[:tool_id])

  # Checks delivery settings for the tool to populate the select field in the form.
  # Rentals require one specific delivery method, tools with both available need to be formatted.
   if @tool.delivery_options == 'Both'
    # Formats the data for the select field
      @delivery_options = ['Delivery', 'Pickup']
   else 
    # If it's not Both we can juse the delivery option from the Tool itself.
    @delivery_options = [@tool.delivery_options]
   end

  #  Initialize the new rental
   @rental = @tool.rentals.new
  #  Calls the calculate fee method which determines delivery cost based on distance between users and delivery price
   @rental.calculate_fee(current_user)
  #  Stores the owner of the tool being rented as an instance to pass to the view.
   @user = @tool.user
  #  Calls the unavailable dates method to calculate dates which can't be picked.
   @unavailable_dates = @tool.unavailable_dates
  end

  # Rental Creation Logic
  def create
    # Grabs the relevant tool from the database using the id passed in the params.
    @tool = Tool.find(params[:tool_id])
    # Initializes the rental for the current user
    @rental = current_user.rentals.new(rental_params)
    # Sets the tool which the rental belongs to
    @rental.tool = @tool
    # Calculates the delivery fee - although done already we only want to store the ACTUAL delivery fee. Users are sly.
    @rental.calculate_fee(current_user)
    # Pickups dont have a delivery fee.
    if @rental.delivery_option == 'Pickup'
      @rental.delivery_fee = 0
    end

    # Gets the total number of days for the rental
    days = (@rental.end_date - @rental.start_date).to_i
    # Calculates the price - although handled by JS, we only want to store the ACTUAL price based on dates. Users are sly.
    @rental.price = (@rental.tool.price * days)

    # Logic for how to proceed depending on validation of rental
    respond_to do |format|
      if @rental.save
        # Attributes were allowed - rental is saved.
        format.html { redirect_to @rental, notice: 'Your rental has been approved!' }
        format.json { render :show, status: :created, location: @rental }
      else
        # Attributes were not allowed - rental is not saved, try again user.
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # Logic for cancelling rentals
  def destroy

    # Grabs the relevant rental from the database using the id passed in the params
    @rental = Rental.find(params[:id])
    # Rentals less than 24 hours away can't be cancelled - company policy.
    if @rental.start_date > Time.now + 1.day 
      # Cancel the rental
      @rental.destroy
      # Redirect to profile and show success message.
      respond_to do |format|
        format.html { redirect_to '/profile', notice: 'Rental was successfully deleted.' }
      end
    else 
      # Rental start is too close - can't delete, redirect.
      redirect_to(@rental, alert: 'It\'s too late to cancel this rental.')
    end
  end

  # Update Rental Method
  def update
    # Grabs the relevant rental from the database using the id passed in the params
    @rental = Rental.find(params[:id])
    # Checks whether the rental has already been set to complete by the tool owner.
    if update_returned[:returned] == "1"
      # Update rental returned value.
      @rental.returned = true

      # Save the rental and let the user know.
      @rental.save
      redirect_to(@rental, notice: 'Rental Complete - payments will now be processed.')
    end
  end

  # Rental edit page logic
  def edit
    # Grab the relevant rental from the database using the id passed in the params
    @rental = Rental.find(params[:id])

    # Check what the user can do to the rental.
    if can? :delete, @rental
      @rental 

      # If rental updating functionality was finalised - unavailable dates would be passed through to the date picker.
      # @unavailable_dates = @rental.tool.unavailable_dates

    elsif can? :edit, @rental
      @rental
    else
      redirect_to('/browse', alert: 'You do not have permissions to view that page.')
    end
  end

  # Logic for showing Rental page
  def show
    # Grab the relevant rental from the database using the id passed in the params
    @rental = Rental.find(params[:id])
  # Check the user permissions
    if can? :read, @rental
      @rental
    else
      # Failed permission check redirect
      redirect_back(fallback_location: root_path, alert: 'You do not have permissions to view that page.')
    end
  end

  # Rental Index Page
  def index
    # Check permissions - no one gets to see rental details except admins.
    if current_user.has_role?(:admin)
      # No need for a rentals index, redirect to the admin dashboard.
      redirect_to("#{admin_dash_path}#rentals")
    else
      # Failed permissions check redirect
      redirect_to('/browse', alert: 'You do not have permissions to view that page.')
    end
  end

  private

  # Sanitization of rental params for creation.
  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :delivery_option, :price, :delivery_fee)
  end

  # Sanitization of updating returned status.
  def update_returned
    params.require(:rental).permit(:returned)
  end

end

src/mates_rates/app/helpers/rentals_helper.rb
module RentalsHelper
end

src/mates_rates/app/views/rentals/_form.html.erb
  <div class="field col s12 m6">
    <%= form.label :delivery_fee %>
    <%= form.number_field :delivery_fee, disabled: "true" %>
  </div>
  <div class="field col s12 m6">
    <%= form.label :delivery_option %>
    <%# <%= form.select(:delivery_option, @delivery_options ) %> <%#%%>
    <%= form.select(:delivery_option, options_for_select(@delivery_options)) %>
  </div>
  <div class="field col s12">
  <%= form.label :dates %><br>
  <%= form.text_field :dates, id:'dates' %>
</div>

<%= form.hidden_field :start_date, id: 'start_date' %>
<%= form.hidden_field :end_date, id: 'end_date' %>
<%= form.hidden_field :tool_price, id: 'tool_price', value: @tool.price %>

src/mates_rates/app/views/rentals/edit.html.erb
<%= javascript_include_tag 'rentals' %>
<%= javascript_include_tag 'auto_dates' %>



<h1>Manage Rental</h1>

<ul class="collection">
<li class="collection-item">
<% if @rental.user == current_user %>
    <p>Renting  <%= @rental.tool.name %> off <%= link_to "#{@rental.tool.user.first_name}", user_url(@rental.tool.user) %></p>
    <% else %>
    <p>Renting <%= @rental.tool.name %> to <%= link_to "#{@rental.tool.user.first_name}" %></p>
    <% end %>
    <p>From <%= @rental.start_date %> to <%= @rental.end_date %> </p>
    <p>Cost: $<%= @rental.price %>, <%= @rental.delivery_option %><% if @rental.delivery_option == 'Delivery' %>: $<%= @rental.delivery_fee %> for delivery to <%= @rental.user.address %><% end %>
    <% if @rental.delivery_option == 'Pickup' %> from <%= @rental.tool.user.address %></p><% end %>
   <% if can? :delete, @rental %>
   <div class="row">
  <%= link_to 'Cancel Rental', @rental, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-small red darken-3 waves-effect waves-light white-text' %>
  </div>
<% end %>
      <% if @rental.finished %>
<%= form_with model: @rental, url: rental_path(@rental), local: true do |form| %>
  
  <div class="row">
    <div id="returned-field" class="field">
      <label>
        <%= form.check_box :returned, class: "filled-in", id: 'returned', checked: @rental.returned %>
        <span> This tool has been returned. </span>
      </label>
    </div>
  </div>
 
  

   <div class="row" class="center-align col s12">
    <button class="btn-small waves-effect waves-light white-text" type="submit" name="action">Submit
    </div>
 <% end %>
<% end %>

</li>
</ul>  










<h3>Rental Tool</h3>
<div class="card sticky-action hoverable large horizontal">
    <div class="card-image">
      <% if @rental.tool.photo.attached? %>
       <%= image_tag @rental.tool.photo, class: "activator"%>
      <% end %>

    </div>
    <div class="card-content">
      <span class="card-title grey-text text-darken-4"><%= @rental.tool.name %> - <%= @rental.tool.brand %>-<% if @rental.tool.model %><%= @rental.tool.model %><% end %><i class="right red-text darken-4 card-title">$<%= @rental.tool.price %>/day</i></span>
      
      <p>Owned by <%= link_to "#{@rental.tool.user.first_name}", user_url(@rental.tool.user), class: "red-text" %>
      | 
      <% if @rental.tool.delivery_options == 'Both' || @rental.tool.delivery_options == 'Delivery' %>
          Delivery Available - $<%= @rental.tool.delivery_fee%>/km
          <% else %>
          Pickup Only
          <% end %></p>
      <p><%= @rental.tool.description %></p>
    </div>
    <div class="card-action">
          <% if can? :edit, @rental.tool %>
            <%= link_to 'Manage Tool', edit_tool_url(@rental.tool), class: "light-blue waves-effect waves-light btn white-text darken-3"%>
          <% elsif can? :create, Rental %>
            <%= link_to 'Rent this Tool', new_tool_rental_path(@rental.tool), class: "teal waves-effect waves-light btn white-text darken-1" %>
          <% else %>
            <%= link_to 'Sign in to rent this tool', new_user_session_path, class: "cyan waves-effect waves-light btn white-text darken-1" %>
          <% end %>
          
        </div>
  </div>

src/mates_rates/app/views/rentals/new.html.erb
<%= javascript_include_tag 'rentals' %>
<%= javascript_include_tag 'auto_dates' %>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    createDatePicker(JSON.parse('<%= @unavailable_dates.to_json.html_safe %>'))
  })
</script>

<h1>Rent this tool</h1>
<div class="row">
<div class="card sticky-action hoverable small col s12 m6 l4">
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><%= @tool.name %> - <%= @tool.brand %>-<% if @tool.model %><%= @tool.model %><% end %></span>
      <p class="red-text darken-4 card-title">$<%= @tool.price %>/day</p>
      <p>Owned by <%= link_to "#{@tool.user.first_name}", user_url(@tool.user), class: "red-text" %>
      | 
      <% if @tool.delivery_options == 'Both' || @tool.delivery_options == 'Delivery' %>
          Delivery Available - $<%= @tool.delivery_fee%>/km
          <% else %>
          Pickup Only
          <% end %></p>

    </div>
  </div>
<div class="col s12 m6">

<div class="field">
<label>Price</label>
<input disabled="true" type="text" value="" id="price">
</div>

<%= form_with model: @rental, url: tool_rentals_path(@tool), local: true do |form| %>
  <%= render 'form', form: form %>

  
    <div class="row" class="center-align col s12">
    <button class="btn-large waves-effect waves-light white-text" type="submit" name="action">Submit
    </div>
<% end %>
</div>
</div>

src/mates_rates/app/views/rentals/show.html.erb
<h3>Rentals Details</h3>
<ul class="collection">
<li class="collection-item">
<% if @rental.user == current_user %>
    <p>Renting  <%= @rental.tool.name %> off <%= link_to "#{@rental.tool.user.first_name}", user_url(@rental.tool.user) %></p>
    <% else %>
    <p>Renting <%= @rental.tool.name %> to <%= link_to "#{@rental.tool.user.first_name}" %></p>
    <% end %>
    <p>From <%= @rental.start_date %> to <%= @rental.end_date %> </p>
    <p>Cost: $<%= @rental.price %>, <%= @rental.delivery_option %><% if @rental.delivery_option == 'Delivery' %>: $<%= @rental.delivery_fee %> for delivery to <%= @rental.user.address %><% end %>
    <% if @rental.delivery_option == 'Pickup' %> from <%= @rental.tool.user.address %></p><% end %>
    
      <% if can? :delete, @rental %>
        <%= link_to 'Manage Rental', edit_rental_url(@rental), class: "secondary-content btn-small waves-effect waves-light"%>
      <% elsif can? :edit, @rental %>
        <%= link_to 'Manage Rental', edit_rental_url(@rental), class: "secondary-content btn-small waves-effect waves-light"%>
      <% else%>
        <p class="secondary-content">This Rental can no longer be edited.</p>
      <% end %>
      
</li>
</ul>  

<h3>Rental Tool</h3>
<div class="card sticky-action hoverable large horizontal">
    <div class="card-image">
      <% if @rental.tool.photo.attached? %>
       <%= image_tag @rental.tool.photo, class: "activator"%>
      <% end %>

    </div>
    <div class="card-content">
      <span class="card-title grey-text text-darken-4"><%= @rental.tool.name %> - <%= @rental.tool.brand %>-<% if @rental.tool.model %><%= @rental.tool.model %><% end %><i class="right red-text darken-4 card-title">$<%= @rental.tool.price %>/day</i></span>
      
      <p>Owned by <%= link_to "#{@rental.tool.user.first_name}", user_url(@rental.tool.user), class: "red-text" %>
      | 
      <% if @rental.tool.delivery_options == 'Both' || @rental.tool.delivery_options == 'Delivery' %>
          Delivery Available - $<%= @rental.tool.delivery_fee%>/km
          <% else %>
          Pickup Only
          <% end %></p>
      <p><%= @rental.tool.description %></p>
    </div>
    <div class="card-action">
          <% if can? :edit, @rental.tool %>
            <%= link_to 'Manage Tool', edit_tool_url(@rental.tool), class: "light-blue waves-effect waves-light btn white-text darken-3"%>
          <% elsif can? :create, Rental %>
            <%= link_to 'Rent this Tool', new_tool_rental_path(@rental.tool), class: "teal waves-effect waves-light btn white-text darken-1" %>
          <% else %>
            <%= link_to 'Sign in to rent this tool', new_user_session_path, class: "cyan waves-effect waves-light btn white-text darken-1" %>
          <% end %>
          
        </div>
  </div>